FROM mhart/alpine-node:5.6.0

EXPOSE 3000
ENV NODE_ENV development
ENV DB_NAME test
ENV DB_HOST mysql
ENV DB_USER root
ENV DB_PASSWORD test
RUN mkdir /app
WORKDIR /app

# add package.json and run npm install before adding the rest of the files
# this way, you only run npm install when package.json changes
ADD ./app/package.json /app/package.json
RUN npm install
