version: "2"
services:
  wordpress:
    build:
      context: wordpress
      dockerfile: Dockerfile.dev
    environment:
      - WORDPRESS_DB_PASSWORD=test
    depends_on:
      - mysql
    volumes:
      - ./wordpress/:/var/www/html
    ports:
      - 8080:80
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./node_modules/.bin/nodemon server.js
    depends_on:
      - mysql
      - mongodb
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - 80:3000
  # mongodb:
  #   image: tutum/mongodb
  #   ports:
  #     - 27017:27017
  mongodb:
    image: tutum/mongodb
    ports:
      - 27017:27017
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306
  migrations:
    build:
      context: db-migrations
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
  # fixtures:
  #   build:
  #     context: db-fixtures
  #     dockerfile: Dockerfile
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - mysql
